/* tslint:disable */
/* eslint-disable */
/**
 * MathGrass
 * This is the OpenAPI specification for MathGrass
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: andreas.domanowski@tu-dresden.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EvaluateAnswerRequest
 */
export interface EvaluateAnswerRequest {
    /**
     * 
     * @type {string}
     * @memberof EvaluateAnswerRequest
     */
    answer: string;
}

/**
 * Check if a given object implements the EvaluateAnswerRequest interface.
 */
export function instanceOfEvaluateAnswerRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "answer" in value;

    return isInstance;
}

export function EvaluateAnswerRequestFromJSON(json: any): EvaluateAnswerRequest {
    return EvaluateAnswerRequestFromJSONTyped(json, false);
}

export function EvaluateAnswerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvaluateAnswerRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'answer': json['answer'],
    };
}

export function EvaluateAnswerRequestToJSON(value?: EvaluateAnswerRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'answer': value.answer,
    };
}

