/* tslint:disable */
/* eslint-disable */
/**
 * MathGrass
 * This is the OpenAPI specification for MathGrass
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: andreas.domanowski@tu-dresden.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuestionDTO
 */
export interface QuestionDTO {
    /**
     * 
     * @type {string}
     * @memberof QuestionDTO
     */
    question: string;
}

/**
 * Check if a given object implements the QuestionDTO interface.
 */
export function instanceOfQuestionDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "question" in value;

    return isInstance;
}

export function QuestionDTOFromJSON(json: any): QuestionDTO {
    return QuestionDTOFromJSONTyped(json, false);
}

export function QuestionDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'question': json['question'],
    };
}

export function QuestionDTOToJSON(value?: QuestionDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'question': value.question,
    };
}

